# Windowed phase synchrony (wphase) — oracle + contract tests.
#
# PLV formula source: lachaux1999 (p. 195) — PLV = (1/N) |sum_n exp(j theta_n)|
# where theta is the phase difference; see cairn/references/lachaux1999.md.
# bsync adaptation: single-trial, averaged over time samples within a sliding
# window at a lag offset (documented in the reference note and roxygen).

# Helper: wrapped circular difference in (-pi, pi] ----------------------------
wrap_diff <- function(a, b) {
  d <- (a - b + pi) %% (2 * pi) - pi
  # %% maps an exact multiple of 2*pi to -pi; fold that edge case back to pi
  ifelse(d <= -pi, d + 2 * pi, d)
}

# Closed-form oracle (Layer 1 / doctrine type: closed-form) -------------------
#
# For x[t] = cos(w1*t + a), y[t] = cos(w2*t + b), t = 0..n-1, with w1 and w2
# integer-cycle frequencies (w = 2*pi*k/n, 0 < k < n/2), the discrete analytic
# signal is exactly exp(i*(w*t + phase)), so the Hilbert phases are exactly
# w1*t + a and w2*t + b. Phase difference across a window of size w at any
# start/lag advances by dw = w1 - w2 per sample, so
#   PLV = |sum_{k=0}^{w-1} exp(i*dw*k)| / w = |sin(w*dw/2)| / (w*|sin(dw/2)|)
# (the Dirichlet kernel), identical for every window and lag.
#
# Fixture arithmetic (n = 64, k1 = 8, k2 = 6, window_size = 16):
#   w1 = 2*pi*8/64 = pi/4,  w2 = 2*pi*6/64 = 3*pi/16,  dw = pi/16
#   w*dw/2 = 16*(pi/16)/2 = pi/2, so sin(w*dw/2) = 1
#   sin(dw/2) = sin(pi/32) = 0.0980171403...
#   PLV = 1 / (16 * 0.0980171403) = 0.6376435773...
test_that("closed-form oracle: Dirichlet-kernel PLV on integer-cycle cosines (lachaux1999 p. 195)", {
  n <- 64
  t <- 0:(n - 1)
  a <- 0.7
  b <- 0.2
  x <- cos(2 * pi * 8 * t / n + a)
  y <- cos(2 * pi * 6 * t / n + b)

  res <- wphase(x, y, window_size = 16, lag_max = 1)

  plv_expected <- abs(sin(16 * (pi / 16) / 2)) / (16 * abs(sin((pi / 16) / 2)))
  # = 1 / (16 * sin(pi/32)) = 0.637643577350...
  expect_true(all(abs(res$results_df$plv - plv_expected) < 1e-8))

  # rel_phase for the first grid row (i = 2, tau = -1..1): with 1-based series
  # index idx, phi_x[idx] = w1*(idx-1) + a, phi_y[idx+tau] = w2*(idx+tau-1) + b.
  # Circular-mean angle over the window = base + dw*(w-1)/2 where
  # base = w1*(i-1) - w2*(i+tau-1) + (a-b). For i = 2, tau = 0:
  #   base = pi/4 - 3*pi/16 + 0.5 = pi/16 + 0.5
  #   rel  = pi/16 + 0.5 + (pi/16)*7.5 = 0.5 + 8.5*pi/16 = 2.16897...
  row1 <- res$results_df[res$results_df$tau == 0, ][1, ]
  rel_expected <- 0.5 + 8.5 * pi / 16
  expect_true(abs(wrap_diff(row1$rel_phase, rel_expected)) < 1e-8)
})

# Analytic check: identical-frequency sinusoids -> PLV = 1, offset recovered --
test_that("analytic check: fixed phase offset yields PLV ~ 1 and recovers the offset", {
  n <- 128
  t <- 0:(n - 1)
  offset <- 0.9
  x <- cos(2 * pi * 8 * t / n + offset)
  y <- cos(2 * pi * 8 * t / n)

  res <- wphase(x, y, window_size = 32, lag_max = 2)
  tau0 <- res$results_df[res$results_df$tau == 0, ]

  expect_true(all(abs(tau0$plv - 1) < 1e-6))
  expect_true(all(abs(wrap_diff(tau0$rel_phase, offset)) < 1e-6))
})

# Live oracle (doctrine type: live; depth, not bar-clearing — shares
# gsignal::hilbert with the shipped path, so it validates the windowed PLV
# arithmetic, not phase extraction) -------------------------------------------
test_that("live oracle: dumb pure-R windowed PLV matches the shipped path on sim_dyad", {
  x <- sim_dyad$z_A[1:300]
  y <- sim_dyad$z_B[1:300]

  res <- wphase(x, y,
    window_size = 64, lag_max = 8,
    window_increment = 5, lag_increment = 3
  )

  # Deliberately dumb recomputation: explicit loops over hilbert phases.
  phi_x <- Arg(gsignal::hilbert(x))
  phi_y <- Arg(gsignal::hilbert(y))
  w <- 64
  for (r in seq_len(nrow(res$results_df))) {
    i <- res$results_df$i[r]
    tau <- res$results_df$tau[r]
    dphi <- phi_x[i:(i + w - 1)] - phi_y[(i + tau):(i + tau + w - 1)]
    plv_ref <- Mod(mean(exp(1i * dphi)))
    rel_ref <- Arg(mean(exp(1i * dphi)))
    expect_true(abs(res$results_df$plv[r] - plv_ref) < 1e-8)
    expect_true(abs(wrap_diff(res$results_df$rel_phase[r], rel_ref)) < 1e-8)
  }
})

# Simulated-null bound (frozen; generator: data-raw/wphase_null_bound.R) ------
test_that("white-noise PLV stays below the committed simulated-null q99", {
  # Frozen null quantile: q99 of mean_plv over 500 independent white-noise
  # pairs (n = 600, window_size = 96, lag_max = 10, window_increment = 4,
  # lag_increment = 2), master seed 20260829 — generated by
  # data-raw/wphase_null_bound.R (committed; reproduces this value).
  null_q99 <- 0.1316320

  vals <- vapply(1:5, function(seed) {
    set.seed(seed)
    wphase(rnorm(600), rnorm(600),
      window_size = 96, lag_max = 10,
      window_increment = 4, lag_increment = 2
    )$aggregate[["mean_plv"]]
  }, numeric(1))
  # The mean of five independent null draws sits far below the single-draw
  # q99, so this discriminates inflation without the ~5% per-run flake a
  # per-draw q99 comparison would carry (P(any of 5 draws > q99) ~ 1-.99^5).
  expect_lt(mean(vals), null_q99)
})

# AC1: contract — grid geometry, Invariants 4/7/8 -----------------------------
test_that("realized window count and lag set match hand-computed expectations", {
  # n_r = floor((n - w_max - 2*lag_max) / w_inc), w_max = window_size - 1.
  cases <- list(
    # window_size odd, increments 1: n = 100, w_max = 30, n_r = 100-30-10 = 60
    list(n = 100, ws = 31, wi = 1, lm = 5, li = 1, n_r = 60, lags = -5:5),
    # window_size even, window_increment 3: floor((120-39-16)/3) = 21
    list(n = 120, ws = 40, wi = 3, lm = 8, li = 1, n_r = 21, lags = -8:8),
    # lag_increment 3 (asymmetric truncation): seq(-5, 5, 3) = -5 -2 1 4
    list(
      n = 100, ws = 31, wi = 2, lm = 5, li = 3,
      n_r = 30, lags = c(-5L, -2L, 1L, 4L)
    )
  )
  for (cs in cases) {
    set.seed(1)
    res <- wphase(rnorm(cs$n), rnorm(cs$n),
      window_size = cs$ws, window_increment = cs$wi,
      lag_max = cs$lm, lag_increment = cs$li
    )
    expect_equal(length(unique(res$results_df$i)), cs$n_r)
    expect_equal(sort(unique(res$results_df$tau)), sort(cs$lags))
    expect_equal(nrow(res$results_df), cs$n_r * length(cs$lags))
  }
})

test_that("wphase returns the contract classes and light components (Invariant 7)", {
  set.seed(2)
  res <- wphase(rnorm(200), rnorm(200), window_size = 32, lag_max = 4)

  expect_s3_class(res, "wphase_res")
  expect_s3_class(res, "bsync_surface")
  expect_s3_class(res$results_df, "data.frame")
  expect_named(res$results_df, c("i", "tau", "plv", "rel_phase"))
  # Light objects: exactly these components, no cached phase vectors.
  expect_setequal(names(res), c("results_df", "aggregate", "settings"))
  expect_named(res$aggregate, "mean_plv")
  expect_true(is.numeric(res$aggregate[[1]]))
})

test_that("time mapping: window positions map to supplied timestamps (Invariant 8)", {
  set.seed(3)
  n <- 200
  time <- seq(10, by = 0.5, length.out = n)
  res <- wphase(rnorm(n), rnorm(n),
    time = time,
    window_size = 32, lag_max = 4
  )
  res_notime <- wphase(rnorm(n), rnorm(n), window_size = 32, lag_max = 4)

  expect_setequal(unique(res$results_df$i), time[unique(res_notime$results_df$i)])
})

# AC5: NA policy — abort with guidance ----------------------------------------
test_that("wphase aborts on NA-containing input with imputation guidance", {
  set.seed(4)
  n <- 100
  base_x <- rnorm(n)
  base_y <- rnorm(n)

  na_cases <- list(
    x_interior = {
      x <- base_x
      x[50] <- NA
      list(x = x, y = base_y)
    },
    y_interior = {
      y <- base_y
      y[50] <- NA
      list(x = base_x, y = y)
    },
    x_leading = {
      x <- base_x
      x[1] <- NA
      list(x = x, y = base_y)
    },
    x_trailing = {
      x <- base_x
      x[n] <- NA
      list(x = x, y = base_y)
    },
    x_all = list(x = rep(NA_real_, n), y = base_y)
  )

  time_na <- c(NA_real_, seq_len(n - 1))
  expect_error(
    wphase(base_x, base_y, time = time_na, window_size = 31, lag_max = 5),
    regexp = "impute_ts_gaps"
  )

  for (case in na_cases) {
    expect_error(
      wphase(case$x, case$y, window_size = 31, lag_max = 5),
      regexp = "impute_ts_gaps"
    )
  }
})

test_that("wphase validates inputs via the shared validators", {
  expect_error(wphase("a", rnorm(50), window_size = 10, lag_max = 2), regexp = "numeric")
  expect_error(wphase(rnorm(50), rnorm(40), window_size = 10, lag_max = 2), regexp = "length")
  expect_error(wphase(rnorm(50), rnorm(50), window_size = -1, lag_max = 2), regexp = "positive")
  expect_error(wphase(rnorm(50), rnorm(50), window_size = 10, lag_max = 0), regexp = "positive")
  # Short series: build_surface_grid's abort
  expect_error(wphase(rnorm(20), rnorm(20), window_size = 15, lag_max = 5), regexp = "too short")
})

# AC4/AC6: superclass methods, optima and leadership --------------------------
test_that("tidy/glance/as_tibble return superclass shapes on wphase_res", {
  res <- wphase(sim_dyad$z_A[1:300], sim_dyad$z_B[1:300],
    window_size = 64, lag_max = 5, window_increment = 8
  )

  td <- generics::tidy(res)
  expect_equal(nrow(td), nrow(res$results_df))
  expect_true(all(c("i", "tau", "plv", "rel_phase") %in% names(td)))

  gl <- generics::glance(res)
  expect_equal(nrow(gl), 1L)
  expect_true(all(
    c("window_size", "window_increment", "lag_max", "lag_increment", "statistic") %in% names(gl)
  ))
  expect_equal(gl$window_size, 64)
  expect_equal(gl$statistic, "mean_plv")
  expect_equal(gl$mean_plv, res$aggregate[["mean_plv"]])

  tb <- tibble::as_tibble(res)
  expect_s3_class(tb, "tbl_df")
  expect_equal(nrow(tb), nrow(res$results_df))
})

test_that("pick_optima and leadership_asymmetry accept wphase surfaces", {
  res <- wphase(sim_dyad$z_A[1:300], sim_dyad$z_B[1:300],
    window_size = 64, lag_max = 5, window_increment = 8
  )

  opt_local <- pick_optima(res, L_size = 3)
  expect_s3_class(opt_local, "wphase_optima")
  expect_true(all(c("i", "optimum_lag", "optimum_value") %in% names(opt_local)))
  # The local search actually yields optima on this surface (not all-NA)
  expect_gt(sum(!is.na(opt_local$optimum_value)), 0)
  expect_true(all(opt_local$optimum_value >= 0, na.rm = TRUE))

  opt_global <- pick_optima(res, search_method = "global")
  expect_s3_class(opt_global, "wphase_optima")
  # Global search returns each window's max PLV
  by_win <- tapply(res$results_df$plv, res$results_df$i, max)
  expect_equal(unname(opt_global$optimum_value), as.vector(by_win[as.character(opt_global$i)]))

  lai <- leadership_asymmetry(opt_local, epoch_size = 6)
  expect_true(all(c("i", "asymmetry_index") %in% names(lai)))
  expect_gt(sum(!is.na(lai$asymmetry_index)), 0)
  expect_true(all(abs(lai$asymmetry_index) <= 1, na.rm = TRUE))
})

test_that("print and summary methods run for wphase objects", {
  res <- wphase(sim_dyad$z_A[1:300], sim_dyad$z_B[1:300],
    window_size = 64, lag_max = 5, window_increment = 8
  )
  expect_message(print(res), "Windowed Phase Synchrony Analysis")
  expect_message(summary(res), "Phase-Locking Value Distribution")

  set.seed(7)
  ys <- generate_surrogate_circular(sim_dyad$z_B[1:300], n_surrogates = 9)
  surr <- wphase_surrogate(sim_dyad$z_A[1:300], sim_dyad$z_B[1:300],
    y_surrogates = ys, window_size = 64, lag_max = 5, window_increment = 8
  )
  expect_s3_class(surr, "wphase_surr")
  expect_message(print(surr), "Windowed Phase Synchrony Surrogate Analysis")

  opt <- pick_optima(res, L_size = 3)
  expect_message(print(opt), "Windowed Phase Synchrony Optima")
  expect_message(summary(opt), "Optimum Lag Distribution")
})

# Selectable aggregate statistic ---------------------------------------------
#
# Closed-form oracle for statistic = "peak": the definition wcc_aggregate()
# uses for wcc's "peak" (R/wcc.R), applied to PLV. An explicit loop over the
# Hilbert phases finds every window start that fits (start i with
# i - lag_max >= 1 and i + window_size - 1 + lag_max <= n), takes the largest
# PLV across lags in each window, and averages those per-window values.
peak_plv_loop <- function(x, y, ws, lag_max, wi = 1, li = 1) {
  phi_x <- Arg(gsignal::hilbert(x))
  phi_y <- Arg(gsignal::hilbert(y))
  n <- length(x)
  lags <- seq(-lag_max, lag_max, by = li)
  starts <- integer(0)
  i <- 1 + lag_max
  while (i + ws - 1 + lag_max <= n) {
    starts <- c(starts, i)
    i <- i + wi
  }
  peaks <- numeric(length(starts))
  for (r in seq_along(starts)) {
    best <- -Inf
    for (tau in lags) {
      s <- starts[r]
      dphi <- phi_x[s:(s + ws - 1)] - phi_y[(s + tau):(s + tau + ws - 1)]
      best <- max(best, Mod(mean(exp(1i * dphi))))
    }
    peaks[r] <- best
  }
  mean(peaks)
}

# Case (a): default increments, no time. y keeps a constant phase offset from
# x in its first half and runs at another frequency in its second half, so
# windows range from full locking to drifting phases.
# Case (b): window_increment = 2, lag_increment = 3 with lag_max = 5 (lags
# -5, -2, 1, 4), and a time vector in which window starts 6 and 8 (the first
# two, at 1 + lag_max and one increment later) share a timestamp. n = 201 makes n - window_size - 2 * lag_max odd, so the window
# count does not depend on how a partial last step is counted.
stat_cases <- function() {
  t <- 0:79
  y_a <- c(
    cos(2 * pi * 5 * t[1:40] / 80 + 0.6),
    cos(2 * pi * 9 * t[41:80] / 80)
  )
  time_b <- as.numeric(seq_len(201))
  time_b[8] <- time_b[6]
  list(
    a = list(
      x = cos(2 * pi * 5 * t / 80), y = y_a, time = NULL,
      ws = 16, lm = 2, wi = 1, li = 1
    ),
    b = list(
      x = sim_dyad$z_A[1:201], y = sim_dyad$z_B[1:201], time = time_b,
      ws = 32, lm = 5, wi = 2, li = 3
    )
  )
}

run_wphase_case <- function(cs, y = cs$y, ...) {
  wphase(cs$x, y,
    time = cs$time, window_size = cs$ws, lag_max = cs$lm,
    window_increment = cs$wi, lag_increment = cs$li, ...
  )
}

test_that("statistic = 'peak' matches the explicit-loop oracle; default stays the mean PLV", {
  for (cs in stat_cases()) {
    peak_ref <- peak_plv_loop(cs$x, cs$y, cs$ws, cs$lm, cs$wi, cs$li)
    res_peak <- run_wphase_case(cs, statistic = "peak")
    expect_lt(abs(res_peak$aggregate[[1]] - peak_ref), 1e-12)

    res_default <- run_wphase_case(cs)
    expect_identical(
      res_default$aggregate[[1]],
      base::mean(res_default$results_df$plv, na.rm = TRUE)
    )
  }
})

test_that("wphase_surrogate matches the null to the observed statistic", {
  for (cs in stat_cases()) {
    set.seed(11)
    ys <- generate_surrogate_circular(cs$y, n_surrogates = 3)
    for (st in c("mean_plv", "peak")) {
      surr <- wphase_surrogate(cs$x, cs$y,
        y_surrogates = ys, time = cs$time,
        window_size = cs$ws, lag_max = cs$lm,
        window_increment = cs$wi, lag_increment = cs$li,
        statistic = st
      )
      for (j in 1:3) {
        ref_j <- run_wphase_case(cs, y = ys[, j], statistic = st)$aggregate[[1]]
        expect_lt(abs(surr$surrogate_z[j] - ref_j), 1e-12)
      }
      if (st == "peak") {
        peak_ref <- peak_plv_loop(cs$x, cs$y, cs$ws, cs$lm, cs$wi, cs$li)
        expect_lt(abs(surr$observed_z - peak_ref), 1e-12)
      }
    }
  }
})

test_that("an unknown statistic stops wphase and wphase_surrogate", {
  x <- sim_dyad$z_A[1:120]
  y <- sim_dyad$z_B[1:120]
  expect_error(
    wphase(x, y, window_size = 32, lag_max = 4, statistic = "median"),
    "should be one of"
  )
  ys <- matrix(y, ncol = 1)
  expect_error(
    wphase_surrogate(x, y,
      y_surrogates = ys, window_size = 32, lag_max = 4,
      statistic = "median"
    ),
    "should be one of"
  )
})
