# Windowed phase synchrony (wphase) — oracle + contract tests.
#
# PLV formula source: lachaux1999 (p. 195) — PLV = (1/N) |sum_n exp(j theta_n)|
# where theta is the phase difference; see cairn/references/lachaux1999.md.
# bsync adaptation: single-trial, averaged over time samples within a sliding
# window at a lag offset (documented in the reference note and roxygen).

# Helper: wrapped circular difference in (-pi, pi] ----------------------------
wrap_diff <- function(a, b) {
  d <- (a - b + pi) %% (2 * pi) - pi
  # %% maps an exact multiple of 2*pi to -pi; fold that edge case back to pi
  ifelse(d <= -pi, d + 2 * pi, d)
}

# Closed-form oracle (Layer 1 / doctrine type: closed-form) -------------------
#
# For x[t] = cos(w1*t + a), y[t] = cos(w2*t + b), t = 0..n-1, with w1 and w2
# integer-cycle frequencies (w = 2*pi*k/n, 0 < k < n/2), the discrete analytic
# signal is exactly exp(i*(w*t + phase)), so the Hilbert phases are exactly
# w1*t + a and w2*t + b. Phase difference across a window of size w at any
# start/lag advances by dw = w1 - w2 per sample, so
#   PLV = |sum_{k=0}^{w-1} exp(i*dw*k)| / w = |sin(w*dw/2)| / (w*|sin(dw/2)|)
# (the Dirichlet kernel), identical for every window and lag.
#
# Fixture arithmetic (n = 64, k1 = 8, k2 = 6, window_size = 16):
#   w1 = 2*pi*8/64 = pi/4,  w2 = 2*pi*6/64 = 3*pi/16,  dw = pi/16
#   w*dw/2 = 16*(pi/16)/2 = pi/2, so sin(w*dw/2) = 1
#   sin(dw/2) = sin(pi/32) = 0.0980171403...
#   PLV = 1 / (16 * 0.0980171403) = 0.6376435773...
test_that("closed-form oracle: Dirichlet-kernel PLV on integer-cycle cosines (lachaux1999 p. 195)", {
  n <- 64
  t <- 0:(n - 1)
  a <- 0.7
  b <- 0.2
  x <- cos(2 * pi * 8 * t / n + a)
  y <- cos(2 * pi * 6 * t / n + b)

  res <- wphase(x, y, window_size = 16, lag_max = 1)

  plv_expected <- abs(sin(16 * (pi / 16) / 2)) / (16 * abs(sin((pi / 16) / 2)))
  # = 1 / (16 * sin(pi/32)) = 0.637643577350...
  expect_true(all(abs(res$results_df$plv - plv_expected) < 1e-8))

  # rel_phase for the first grid row (i = 2, tau = -1..1): with 1-based series
  # index idx, phi_x[idx] = w1*(idx-1) + a, phi_y[idx+tau] = w2*(idx+tau-1) + b.
  # Circular-mean angle over the window = base + dw*(w-1)/2 where
  # base = w1*(i-1) - w2*(i+tau-1) + (a-b). For i = 2, tau = 0:
  #   base = pi/4 - 3*pi/16 + 0.5 = pi/16 + 0.5
  #   rel  = pi/16 + 0.5 + (pi/16)*7.5 = 0.5 + 8.5*pi/16 = 2.16897...
  row1 <- res$results_df[res$results_df$tau == 0, ][1, ]
  rel_expected <- 0.5 + 8.5 * pi / 16
  expect_true(abs(wrap_diff(row1$rel_phase, rel_expected)) < 1e-8)
})

# Analytic check: identical-frequency sinusoids -> PLV = 1, offset recovered --
test_that("analytic check: fixed phase offset yields PLV ~ 1 and recovers the offset", {
  n <- 128
  t <- 0:(n - 1)
  offset <- 0.9
  x <- cos(2 * pi * 8 * t / n + offset)
  y <- cos(2 * pi * 8 * t / n)

  res <- wphase(x, y, window_size = 32, lag_max = 2)
  tau0 <- res$results_df[res$results_df$tau == 0, ]

  expect_true(all(abs(tau0$plv - 1) < 1e-6))
  expect_true(all(abs(wrap_diff(tau0$rel_phase, offset)) < 1e-6))
})

# Live oracle (doctrine type: live; depth, not bar-clearing — shares
# gsignal::hilbert with the shipped path, so it validates the windowed PLV
# arithmetic, not phase extraction) -------------------------------------------
test_that("live oracle: dumb pure-R windowed PLV matches the shipped path on sim_dyad", {
  x <- sim_dyad$z_A[1:300]
  y <- sim_dyad$z_B[1:300]

  res <- wphase(x, y,
    window_size = 64, lag_max = 8,
    window_increment = 5, lag_increment = 3
  )

  # Deliberately dumb recomputation: explicit loops over hilbert phases.
  phi_x <- Arg(gsignal::hilbert(x))
  phi_y <- Arg(gsignal::hilbert(y))
  w <- 64
  for (r in seq_len(nrow(res$results_df))) {
    i <- res$results_df$i[r]
    tau <- res$results_df$tau[r]
    dphi <- phi_x[i:(i + w - 1)] - phi_y[(i + tau):(i + tau + w - 1)]
    plv_ref <- Mod(mean(exp(1i * dphi)))
    rel_ref <- Arg(mean(exp(1i * dphi)))
    expect_true(abs(res$results_df$plv[r] - plv_ref) < 1e-8)
    expect_true(abs(wrap_diff(res$results_df$rel_phase[r], rel_ref)) < 1e-8)
  }
})

# Simulated-null bound (frozen; generator: data-raw/wphase_null_bound.R) ------
test_that("white-noise PLV stays below the committed simulated-null q99", {
  # Frozen null quantile: q99 of mean_plv over 500 independent white-noise
  # pairs (n = 600, window_size = 96, lag_max = 10, window_increment = 4,
  # lag_increment = 2), master seed 20260829 — generated by
  # data-raw/wphase_null_bound.R (committed; reproduces this value).
  null_q99 <- 0.1316320

  for (seed in 1:5) {
    set.seed(seed)
    x <- rnorm(600)
    y <- rnorm(600)
    res <- wphase(x, y,
      window_size = 96, lag_max = 10,
      window_increment = 4, lag_increment = 2
    )
    expect_lt(res$aggregate[["mean_plv"]], null_q99)
  }
})

# AC1: contract — grid geometry, Invariants 4/7/8 -----------------------------
test_that("realized window count and lag set match hand-computed expectations", {
  # n_r = floor((n - w_max - 2*lag_max) / w_inc), w_max = window_size - 1.
  cases <- list(
    # window_size odd, increments 1: n = 100, w_max = 30, n_r = 100-30-10 = 60
    list(n = 100, ws = 31, wi = 1, lm = 5, li = 1, n_r = 60, lags = -5:5),
    # window_size even, window_increment 3: floor((120-39-16)/3) = 21
    list(n = 120, ws = 40, wi = 3, lm = 8, li = 1, n_r = 21, lags = -8:8),
    # lag_increment 3 (asymmetric truncation): seq(-5, 5, 3) = -5 -2 1 4
    list(
      n = 100, ws = 31, wi = 2, lm = 5, li = 3,
      n_r = floor((100 - 30 - 10) / 2), lags = c(-5L, -2L, 1L, 4L)
    )
  )
  for (cs in cases) {
    set.seed(1)
    res <- wphase(rnorm(cs$n), rnorm(cs$n),
      window_size = cs$ws, window_increment = cs$wi,
      lag_max = cs$lm, lag_increment = cs$li
    )
    expect_equal(length(unique(res$results_df$i)), cs$n_r)
    expect_equal(sort(unique(res$results_df$tau)), sort(cs$lags))
    expect_equal(nrow(res$results_df), cs$n_r * length(cs$lags))
  }
})

test_that("wphase returns the contract classes and light components (Invariant 7)", {
  set.seed(2)
  res <- wphase(rnorm(200), rnorm(200), window_size = 32, lag_max = 4)

  expect_s3_class(res, "wphase_res")
  expect_s3_class(res, "bsync_surface")
  expect_s3_class(res$results_df, "data.frame")
  expect_named(res$results_df, c("i", "tau", "plv", "rel_phase"))
  # Light objects: exactly these components, no cached phase vectors.
  expect_setequal(names(res), c("results_df", "aggregate", "settings"))
  expect_named(res$aggregate, "mean_plv")
  expect_true(is.numeric(res$aggregate[[1]]))
})

test_that("time mapping: window positions map to supplied timestamps (Invariant 8)", {
  set.seed(3)
  n <- 200
  time <- seq(10, by = 0.5, length.out = n)
  res <- wphase(rnorm(n), rnorm(n),
    time = time,
    window_size = 32, lag_max = 4
  )
  res_notime <- wphase(rnorm(n), rnorm(n), window_size = 32, lag_max = 4)

  expect_setequal(unique(res$results_df$i), time[unique(res_notime$results_df$i)])
})

# AC5: NA policy — abort with guidance ----------------------------------------
test_that("wphase aborts on NA-containing input with imputation guidance", {
  set.seed(4)
  n <- 100
  base_x <- rnorm(n)
  base_y <- rnorm(n)

  na_cases <- list(
    x_interior = {
      x <- base_x
      x[50] <- NA
      list(x = x, y = base_y)
    },
    y_interior = {
      y <- base_y
      y[50] <- NA
      list(x = base_x, y = y)
    },
    x_leading = {
      x <- base_x
      x[1] <- NA
      list(x = x, y = base_y)
    },
    x_trailing = {
      x <- base_x
      x[n] <- NA
      list(x = x, y = base_y)
    },
    x_all = list(x = rep(NA_real_, n), y = base_y)
  )

  for (case in na_cases) {
    expect_error(
      wphase(case$x, case$y, window_size = 31, lag_max = 5),
      regexp = "impute_ts_gaps"
    )
  }
})

test_that("wphase validates inputs via the shared validators", {
  expect_error(wphase("a", rnorm(50), window_size = 10, lag_max = 2), regexp = "numeric")
  expect_error(wphase(rnorm(50), rnorm(40), window_size = 10, lag_max = 2), regexp = "length")
  expect_error(wphase(rnorm(50), rnorm(50), window_size = -1, lag_max = 2), regexp = "positive")
  expect_error(wphase(rnorm(50), rnorm(50), window_size = 10, lag_max = 0), regexp = "positive")
  # Short series: build_surface_grid's abort
  expect_error(wphase(rnorm(20), rnorm(20), window_size = 15, lag_max = 5), regexp = "too short")
})
